import type { Metadata } from "next";
import { Inter, Merriweather, JetBrains_Mono} from "next/font/google";
import "./globals.css";
import LocationProvider from "./context/LocationProvider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const marriweather = Merriweather({
  variable: "--font-merriweather",
  subsets: ["latin"],
  weight: "300"
});

const jetBrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Weather App",
  icons: {
    icon: "/Sunny_Clouds.svg",
    shortcut: "/Sunny_Clouds.svg",
    apple: "/Sunny_Clouds.svg",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <LocationProvider>
      <body
        className={`${inter.variable} ${marriweather.variable} ${jetBrainsMono.variable} antialiased`}
      >
        {children} 
      </body>
      </LocationProvider>
    </html>
  );
}
